### PR TITLE
Electronics done

### PR DESCRIPTION
**Pull request by MikeMihailov**
All electronics parts have developed and tested.

### CODE REVIEW

**Comment by prgrobots** [comment]
> All electronics parts have developed and tested.

Is this for the closed loop stepper board?
I noticed that there were some files that were setup for production, can I email you about this or are you ok to answer questions here

Thanks

**Comment by MikeMihailov** [comment]
> > All electronics parts have developed and tested.
> 
> Is this for the closed loop stepper board? I noticed that there were some files that were setup for production, can I email you about this or are you ok to answer questions here
> 
> Thanks

There are two boards: stepper controller and raspberry pi hat.
There are files for production:
1. https://github.com/marcostrullato/open_niryo_one/tree/develop/Electronics/Stepper/OUT/R2
2. https://github.com/marcostrullato/open_niryo_one/tree/develop/Electronics/RPi_adapter/OUT/R2

If you have any questions you can email me. Feel free.

**Comment by prgrobots** [comment]
Wow, the work you have done on this project is amazing.

**Review by marcostrullato — APPROVED** [review]

**Comment by marcostrullato** [comment]
Merging into master

**Pull request merged**
